### ISSUE TITLE
[BUG] Port scanning not working as expected

### ISSUE THREAD

**Issue by orkhanshirin** [zeldegiz/mytool#1]
I tried to sniff for my device's open ports: `./mytool scanner portscanner scan 192.168.1.12 8079 8090 5`
At that time I was using port number: 8080 actively. But the tools show it's closed

**Comment by zeldegiz** [comment]
I test this situation and worked on my computer. Please test `./mytool scanner portscanner scan localhost 8079 8090 5` command and share result with us

**Comment by orkhanshirin** [comment]
Yeah, that worked. Thanks
