### ISSUE TITLE
[BUG] Permission error on local devicelister

### ISSUE THREAD

**Issue by orkhanshirin** [zeldegiz/mytool#2]
Don't know which permissions are needed to use that feature. A hint for that permissions would be helpful. Ideally expected to solve all needed permissions without asking the user.

**Comment by zeldegiz** [comment]
You do not need any permissions to list users on network. If you use docker must add --net=host for using same network and seeing each-other

**Comment by orkhanshirin** [comment]
I'm testing it directly. Not using docker.
The OS that I'm using is Linux Ubuntu 20.04 LTS

**Comment by orkhanshirin** [comment]
The error is still active. 
Besides, the general layout of the project needs to be more self-explanatory and preferably intuitive. 
The Command List explanations in Readme would be helpful to users.
I'll put my humble example for reference. If it helps that'll be great.

https://github.com/orkhanshirin/bst_assignment/blob/final/README.md

Please consider the general layout of the example.

**Comment by zeldegiz** [comment]
If you use this application in virtual vps on some hosting, this can cause a problem. Because devicelister function send ARP request to other ips and hosting service didn't allow it. Same time, some network devices block arp request, so this may be the cause of the problem

**Comment by zeldegiz** [comment]
Thanks for the advice. Considering the link you sent, I will try to improve my readme file

**Comment by zeldegiz** [comment]
Please test `chmod u+x ./mytool` command for test permission denied error solve
